import copy

from nero.ui.face.expression_profile import ExpressionProfile
from nero.ui.face.face_state import FaceState


DEFAULT_EXPRESSION_LIBRARY = {
    FaceState.IDLE: ExpressionProfile(
        name="IDLE",
        width_scale=1.0,
        height_scale=1.0,
        offset_x=0.0,
        offset_y=0.0,
        corner_radius=28.0,
        idle_enabled=True,
        idle_amplitude_x=100.0,
        idle_amplitude_y=100.0,
        blink_enabled=True,
        blink_min_interval_frames=70,
        blink_max_interval_frames=170,
        blink_duration_frames=5,
        eyelid_tired=0.0,
        eyelid_angry=0.0,
        eyelid_happy=0.0,
    ),
    FaceState.LISTENING: ExpressionProfile(
        name="LISTENING",
        width_scale=1.02,
        height_scale=1.22,
        offset_x=0.0,
        offset_y=-8.0,
        corner_radius=28.0,
        idle_enabled=False,
        blink_enabled=True,
        blink_min_interval_frames=90,
        blink_max_interval_frames=190,
        blink_duration_frames=4,
        eyelid_tired=0.0,
        eyelid_angry=0.0,
        eyelid_happy=0.0,
    ),
    FaceState.THINKING: ExpressionProfile(
        name="THINKING",
        width_scale=1.10,
        height_scale=0.58,
        offset_x=0.0,
        offset_y=10.0,
        corner_radius=24.0,
        idle_enabled=False,
        blink_enabled=True,
        blink_min_interval_frames=110,
        blink_max_interval_frames=220,
        blink_duration_frames=4,
        thinking_drift=True,
        eyelid_tired=0.18,
        eyelid_angry=0.0,
        eyelid_happy=0.0,
    ),
    FaceState.SPEAKING: ExpressionProfile(
        name="SPEAKING",
        width_scale=1.0,
        height_scale=0.95,
        offset_x=0.0,
        offset_y=0.0,
        corner_radius=28.0,
        idle_enabled=False,
        blink_enabled=True,
        blink_min_interval_frames=80,
        blink_max_interval_frames=170,
        blink_duration_frames=4,
        speaking_pulse=True,
        eyelid_tired=0.0,
        eyelid_angry=0.0,
        eyelid_happy=0.0,
    ),
    FaceState.HAPPY: ExpressionProfile(
        name="HAPPY",
        width_scale=1.02,
        height_scale=0.72,
        offset_x=0.0,
        offset_y=8.0,
        corner_radius=30.0,
        idle_enabled=True,
        idle_amplitude_x=12.0,
        idle_amplitude_y=6.0,
        blink_enabled=True,
        blink_min_interval_frames=80,
        blink_max_interval_frames=170,
        blink_duration_frames=4,
        eyelid_tired=0.0,
        eyelid_angry=0.0,
        eyelid_happy=0.42,
    ),
    FaceState.TIRED: ExpressionProfile(
        name="TIRED",
        width_scale=1.04,
        height_scale=0.42,
        offset_x=0.0,
        offset_y=16.0,
        corner_radius=22.0,
        idle_enabled=False,
        blink_enabled=True,
        blink_min_interval_frames=35,
        blink_max_interval_frames=80,
        blink_duration_frames=8,
        eyelid_tired=0.45,
        eyelid_angry=0.0,
        eyelid_happy=0.0,
    ),
    FaceState.ANGRY: ExpressionProfile(
        name="ANGRY",
        width_scale=1.12,
        height_scale=0.62,
        offset_x=0.0,
        offset_y=6.0,
        corner_radius=18.0,
        idle_enabled=False,
        blink_enabled=True,
        blink_min_interval_frames=90,
        blink_max_interval_frames=180,
        blink_duration_frames=4,
        eyelid_tired=0.0,
        eyelid_angry=0.42,
        eyelid_happy=0.0,
    ),
    FaceState.CONFUSED: ExpressionProfile(
        name="CONFUSED",
        width_scale=1.0,
        height_scale=0.88,
        offset_x=0.0,
        offset_y=2.0,
        corner_radius=28.0,
        idle_enabled=False,
        blink_enabled=True,
        blink_min_interval_frames=90,
        blink_max_interval_frames=180,
        blink_duration_frames=4,
        asymmetry_offset_y_left=-6.0,
        asymmetry_offset_y_right=6.0,
        asymmetry_height_left=1.05,
        asymmetry_height_right=0.82,
        eyelid_tired=0.0,
        eyelid_angry=0.10,
        eyelid_happy=0.0,
    ),
}


def make_expression_library():
    return {state: copy.deepcopy(profile) for state, profile in DEFAULT_EXPRESSION_LIBRARY.items()}